### ISSUE TITLE
Error finding declaration

### ISSUE THREAD

**Issue by AokazeDev** [carlosfdezb/tioanime#1]
Hi, i tried to use your api, but when try to declare, i have this error: 
Could not find a declaration file for module 'tioanime'. 'tioanime/src/api.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/tioanime` if it exists or add a new declaration (.d.ts) file containing `declare module 'tioanime';`ts(7016)

**Comment by carlosfdezb** [comment]
hello, I added the ts definitions, sorry for waiting, if your problem is still not fixed, I will gladly continue to help you
